<a href="https://colab.research.google.com/github/biswalsaroj/Data_Science/blob/main/Assignment_session_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [8]:
CUSTOMER_MASTER=pd.read_excel(r'https://raw.githubusercontent.com/biswalsaroj/Data_Science/refs/heads/main/CUSTOMER_MASTER.xlsx')
CUSTOMER_MASTER

,CUSTOMER_ID,CUSTOMER NAME,CUSTOMER_SSN,CITY,MARKET,DOB,TOWN
0,1000032547,Rick Hansen,RH-19495,New York City,US,1984-09-15,Kyabram
1,1000032548,Justin Ritter,JR-16210,Wollongong,APAC,1974-07-15,Hawthorn East
2,1000032549,Craig Reiter,CR-12730,Brisbane,APAC,1959-04-01,Revesby
3,1000032550,Katherine Murray,KM-16375,Berlin,EU,1978-05-16,Willow Grove
4,1000032551,Rick Hansen,RH-9495,Dakar,Africa,1978-12-16,mona vale
5,1000032552,Jim Mitchum,NaN,Sydney,APAC,1987-07-21,Rowville
6,1000032553,Toby Swindell,TS-21340,Porirua,APAC,1986-11-07,MINNAMURRA
7,1000032554,Mick Brown,MB-18085,Hamilton,APAC,1987-04-29,Lake Illawarra
8,1000032555,Jane Waco,JW-15220,Sacramento,US,1958-03-04,Vermont South
9,1000032556,Joseph Holt,JH-15985,Concord,US,1952-08-15,Blackburn Nth
10,1000032557,Greg Maxwell,GM-14695,Alexandria,US,1984-12-26,Rowville
11,1000032558,Anthony Jacobs,AJ-10780,NaN,APAC,1956-02-17,Box Hill North
12,1000032559,Magdelene Morse,MM-7260,Jizan,EMEA,1979-04-11,FOREST HILL
13,1000032560,Vicky Freymann,VF-21715,Toledo,LATAM,1985-03-12,BERWICK
14,1000032561,Peter Fuller,PF-19120,Mudanjiang,APAC,NaT,Buderim
15,1000032562,Ben Peterman,BP-11185,Paris,EU,1952-01-10,NaN
16,1000032563,Thomas Boland,TB-21175,Henderson,US,1965-07-10,scarness
17,1000032564,Patrick Jones,PJ-18835,Prato,EU,1948-07-20,Kuluin
18,1000032565,Jim Sink,NaN,Townsville,APAC,1949-09-30,Menai
19,1000032566,Ritsa Hightower,RH-9555,Uvinza,Africa,1948-10-21,NaN
20,1000032567,Ann Blume,AB-600,Bytom,EMEA,1972-05-31,BARRACK HEIGHTS

In [ ]:
#GET NUMBER OF COLUMNS AND RECORDS IN THE DATASET

In [9]:
CUSTOMER_MASTER.shape

(21, 7)

In [ ]:
#GET THE LIST OF COLUMNS HEADERS NAME

In [10]:
CUSTOMER_MASTER.columns

Index(['CUSTOMER_ID', 'CUSTOMER NAME', 'CUSTOMER_SSN', 'CITY', 'MARKET', 'DOB',
       'TOWN'],
      dtype='object')

In [ ]:
#GET FIRST 3 RECORDS FROM THE DATASET

In [11]:
CUSTOMER_MASTER.head(3)

,CUSTOMER_ID,CUSTOMER NAME,CUSTOMER_SSN,CITY,MARKET,DOB,TOWN
0,1000032547,Rick Hansen,RH-19495,New York City,US,1984-09-15,Kyabram
1,1000032548,Justin Ritter,JR-16210,Wollongong,APAC,1974-07-15,Hawthorn East
2,1000032549,Craig Reiter,CR-12730,Brisbane,APAC,1959-04-01,Revesby

In [ ]:
#GET LAST 3 RECORDS FROM THE DATASET

In [12]:
CUSTOMER_MASTER.tail(3)

,CUSTOMER_ID,CUSTOMER NAME,CUSTOMER_SSN,CITY,MARKET,DOB,TOWN
18,1000032565,Jim Sink,NaN,Townsville,APAC,1949-09-30,Menai
19,1000032566,Ritsa Hightower,RH-9555,Uvinza,Africa,1948-10-21,NaN
20,1000032567,Ann Blume,AB-600,Bytom,EMEA,1972-05-31,BARRACK HEIGHTS

In [ ]:
#GET VARIABLES DATA TYPES

In [13]:
CUSTOMER_MASTER.dtypes

CUSTOMER_ID               int64
CUSTOMER NAME            object
CUSTOMER_SSN             object
CITY                     object
MARKET                   object
DOB              datetime64[ns]
TOWN                     object
dtype: object

In [ ]:
#GET THE TOTAL MISSING RECORDS IN THE DATASET

In [15]:
CUSTOMER_MASTER.isnull().sum().sum()

np.int64(6)

In [ ]:
#GET THE TOTAL MISSING RECORDS IN THE VARIABLE CUSTOMER_SSN

In [16]:
CUSTOMER_MASTER['CUSTOMER_SSN'].isnull().sum().sum()

np.int64(2)

# **Task-3**

In [17]:
ACCOUNT_PERF_CSV=pd.read_csv(r'https://raw.githubusercontent.com/biswalsaroj/Data_Science/refs/heads/main/ACCOUNT_PERF_DATA.csv')
ACCOUNT_PERF_CSV

,Account_number,PORTFOLIO,SSN,Phone No.,Place Name,County,City,State,Zip,Region,Account Open Date,Loan_amount,Loan_status,Last_payment_date,Origination_fico_score,Current_fico_score,Current_outstanding
0,38673575,CREDIT CARD,640-29-9264,405-775-9884,Bromide,Johnston,Bromide,OK,74530,South,13-03-18,"$40,169",Non-Default,27-11-20,732,779,"$1,607"
1,38673576,PERSONAL LOAN,375-37-8517,212-786-7533,Reading Center,Schuyler,Reading Center,NY,14876,Northeast,23-06-19,"$187,055",Non-Default,24-08-21,877,877,"$1,871"
2,38673577,PERSONAL LOAN,073-02-5563,385-775-0225,Ibapah,Tooele,Ibapah,UT,84034,West,08-09-19,"$129,073",Non-Default,10-04-21,875,881,"$16,779"
3,38673578,MORTGAGE,106-98-7919,216-984-8974,Wickliffe,Lake,Wickliffe,OH,44092,Midwest,20-11-20,"$428,500",Non-Default,08-01-21,708,757,"$145,690"
4,38673579,CREDIT CARD,753-07-4655,217-307-8597,Forrest,Livingston,Forrest,IL,61741,Midwest,20-06-18,"$71,859",Non-Default,24-08-21,714,708,"$16,528"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24999,38698574,CREDIT CARD,112-98-5765,201-857-6904,Wenonah,Gloucester,Wenonah,NJ,8090,Northeast,24-08-21,"$71,581",Non-Default,08-05-21,747,776,"$29,348"
25000,38698575,PERSONAL LOAN,507-57-2035,209-410-5762,West Point,Calaveras,West Point,CA,95255,West,01-09-18,"$110,458",Default,09-01-21,862,906,"$33,137"
25001,38698576,MORTGAGE,094-02-7375,212-698-6318,Syracuse,Onondaga,Syracuse,NY,13225,Northeast,18-04-19,"$796,430",Default,24-08-21,651,684,"$103,536"
25002,38698577,PERSONAL LOAN,467-99-0614,212-525-5734,Woodbury,Nassau,Woodbury,NY,11797,Northeast,15-08-19,"$58,455",Default,28-11-20,878,908,"$22,797"
25003,38698578,MORTGAGE,191-86-1363,229-974-6770,Grovetown,Columbia,Grovetown,GA,30813,South,02-11-20,"$107,454",Non-Default,22-11-20,693,743,"$33,311"

In [21]:
ACCOUNT_PERF_EXCEL=pd.read_excel(r'https://raw.githubusercontent.com/biswalsaroj/Data_Science/refs/heads/main/ACCOUNT_PERF_DATA.xlsx')
ACCOUNT_PERF_EXCEL

,Account_number,PORTFOLIO,SSN,Phone No.,Place Name,County,City,State,Zip,Region,Account Open Date,Loan_amount,Loan_status,Last_payment_date,Origination_fico_score,Current_fico_score,Current_outstanding
0,38673575,CREDIT CARD,640-29-9264,405-775-9884,Bromide,Johnston,Bromide,OK,74530,South,2018-03-13,40169,Non-Default,2020-11-27,732,779,1606.76
1,38673576,PERSONAL LOAN,375-37-8517,212-786-7533,Reading Center,Schuyler,Reading Center,NY,14876,Northeast,2019-06-23,187055,Non-Default,2021-08-24,877,877,1870.55
2,38673577,PERSONAL LOAN,073-02-5563,385-775-0225,Ibapah,Tooele,Ibapah,UT,84034,West,2019-09-08,129073,Non-Default,2021-04-10,875,881,16779.49
3,38673578,MORTGAGE,106-98-7919,216-984-8974,Wickliffe,Lake,Wickliffe,OH,44092,Midwest,2020-11-20,428500,Non-Default,2021-01-08,708,757,145690.00
4,38673579,CREDIT CARD,753-07-4655,217-307-8597,Forrest,Livingston,Forrest,IL,61741,Midwest,2018-06-20,71859,Non-Default,2021-08-24,714,708,16527.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24999,38698574,CREDIT CARD,112-98-5765,201-857-6904,Wenonah,Gloucester,Wenonah,NJ,8090,Northeast,2021-08-24,71581,Non-Default,2021-05-08,747,776,29348.21
25000,38698575,PERSONAL LOAN,507-57-2035,209-410-5762,West Point,Calaveras,West Point,CA,95255,West,2018-09-01,110458,Default,2021-01-09,862,906,33137.40
25001,38698576,MORTGAGE,094-02-7375,212-698-6318,Syracuse,Onondaga,Syracuse,NY,13225,Northeast,2019-04-18,796430,Default,2021-08-24,651,684,103535.90
25002,38698577,PERSONAL LOAN,467-99-0614,212-525-5734,Woodbury,Nassau,Woodbury,NY,11797,Northeast,2019-08-15,58455,Default,2020-11-28,878,908,22797.45
25003,38698578,MORTGAGE,191-86-1363,229-974-6770,Grovetown,Columbia,Grovetown,GA,30813,South,2020-11-02,107454,Non-Default,2020-11-22,693,743,33310.74

In [22]:
ACCOUNT_PERF_EXCEL.columns

Index(['Account_number', 'PORTFOLIO', 'SSN', 'Phone No. ', 'Place Name',
       'County', 'City', 'State', 'Zip', 'Region', 'Account Open Date',
       'Loan_amount', 'Loan_status', 'Last_payment_date',
       'Origination_fico_score', 'Current_fico_score', 'Current_outstanding'],
      dtype='object')

In [44]:
ACCOUNT_PERF_EXCEL.rename(columns={'Phone No. ':'Phone_No','Account Open Date':'Account_Open_Date'}, inplace=True)
ACCOUNT_PERF_EXCEL

,Account_number,PORTFOLIO,SSN,Phone_No,Place Name,County,City,State,Zip,Region,Account_Open_Date,Loan_amount,Loan_status,Last_payment_date,Origination_fico_score,Current_fico_score,Current_outstanding
0,38673575,CREDIT CARD,640-29-9264,405-775-9884,Bromide,Johnston,Bromide,OK,74530,South,2018-03-13,40169,Non-Default,2020-11-27,732,779,1606.76
1,38673576,PERSONAL LOAN,375-37-8517,212-786-7533,Reading Center,Schuyler,Reading Center,NY,14876,Northeast,2019-06-23,187055,Non-Default,2021-08-24,877,877,1870.55
2,38673577,PERSONAL LOAN,073-02-5563,385-775-0225,Ibapah,Tooele,Ibapah,UT,84034,West,2019-09-08,129073,Non-Default,2021-04-10,875,881,16779.49
3,38673578,MORTGAGE,106-98-7919,216-984-8974,Wickliffe,Lake,Wickliffe,OH,44092,Midwest,2020-11-20,428500,Non-Default,2021-01-08,708,757,145690.00
4,38673579,CREDIT CARD,753-07-4655,217-307-8597,Forrest,Livingston,Forrest,IL,61741,Midwest,2018-06-20,71859,Non-Default,2021-08-24,714,708,16527.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24999,38698574,CREDIT CARD,112-98-5765,201-857-6904,Wenonah,Gloucester,Wenonah,NJ,8090,Northeast,2021-08-24,71581,Non-Default,2021-05-08,747,776,29348.21
25000,38698575,PERSONAL LOAN,507-57-2035,209-410-5762,West Point,Calaveras,West Point,CA,95255,West,2018-09-01,110458,Default,2021-01-09,862,906,33137.40
25001,38698576,MORTGAGE,094-02-7375,212-698-6318,Syracuse,Onondaga,Syracuse,NY,13225,Northeast,2019-04-18,796430,Default,2021-08-24,651,684,103535.90
25002,38698577,PERSONAL LOAN,467-99-0614,212-525-5734,Woodbury,Nassau,Woodbury,NY,11797,Northeast,2019-08-15,58455,Default,2020-11-28,878,908,22797.45
25003,38698578,MORTGAGE,191-86-1363,229-974-6770,Grovetown,Columbia,Grovetown,GA,30813,South,2020-11-02,107454,Non-Default,2020-11-22,693,743,33310.74

In [25]:
# WRITE PROGRAM TO CREATE A NEW DATASET AS ACCOUNT_PERF_V1 FROM ACCOUNT_PERF_EXCEL
#keep varibales Account_number
#PORTFOLIO

#SSN

#Phone No.

#City

#State

#Account Open Date

#Loan_amount

#Origination_fico_score

#Current_fico_score

#Current_outstanding '''

In [46]:
 ACCOUNT_PERF_V1=ACCOUNT_PERF_EXCEL[['Account_number','PORTFOLIO','SSN','Phone_No','City','State','Account_Open_Date','Loan_amount','Origination_fico_score','Current_fico_score','Current_outstanding']]
 ACCOUNT_PERF_V1

,Account_number,PORTFOLIO,SSN,Phone_No,City,State,Account_Open_Date,Loan_amount,Origination_fico_score,Current_fico_score,Current_outstanding
0,38673575,CREDIT CARD,640-29-9264,405-775-9884,Bromide,OK,2018-03-13,40169,732,779,1606.76
1,38673576,PERSONAL LOAN,375-37-8517,212-786-7533,Reading Center,NY,2019-06-23,187055,877,877,1870.55
2,38673577,PERSONAL LOAN,073-02-5563,385-775-0225,Ibapah,UT,2019-09-08,129073,875,881,16779.49
3,38673578,MORTGAGE,106-98-7919,216-984-8974,Wickliffe,OH,2020-11-20,428500,708,757,145690.00
4,38673579,CREDIT CARD,753-07-4655,217-307-8597,Forrest,IL,2018-06-20,71859,714,708,16527.57
...,...,...,...,...,...,...,...,...,...,...,...
24999,38698574,CREDIT CARD,112-98-5765,201-857-6904,Wenonah,NJ,2021-08-24,71581,747,776,29348.21
25000,38698575,PERSONAL LOAN,507-57-2035,209-410-5762,West Point,CA,2018-09-01,110458,862,906,33137.40
25001,38698576,MORTGAGE,094-02-7375,212-698-6318,Syracuse,NY,2019-04-18,796430,651,684,103535.90
25002,38698577,PERSONAL LOAN,467-99-0614,212-525-5734,Woodbury,NY,2019-08-15,58455,878,908,22797.45
25003,38698578,MORTGAGE,191-86-1363,229-974-6770,Grovetown,GA,2020-11-02,107454,693,743,33310.74